// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyzJbG5e7qy-m7tsAbIsvx1F0IQNCC1Ek',
    appId: '1:132809015904:web:b581b0f9630abfc8dc7905',
    messagingSenderId: '132809015904',
    projectId: 'digital-garden-de4ed',
    authDomain: 'digital-garden-de4ed.firebaseapp.com',
    storageBucket: 'digital-garden-de4ed.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Mhxe9VO78xJzt6AlKrW5CpBktzkWPck',
    appId: '1:132809015904:android:56630e4223d67308dc7905',
    messagingSenderId: '132809015904',
    projectId: 'digital-garden-de4ed',
    storageBucket: 'digital-garden-de4ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-S9gIlaZ3owwgvbBI2Yx7okYqprVOPms',
    appId: '1:132809015904:ios:151f07a14acaa200dc7905',
    messagingSenderId: '132809015904',
    projectId: 'digital-garden-de4ed',
    storageBucket: 'digital-garden-de4ed.appspot.com',
    iosBundleId: 'nickthecan.com.digitalGarden',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-S9gIlaZ3owwgvbBI2Yx7okYqprVOPms',
    appId: '1:132809015904:ios:001f79f1b8495957dc7905',
    messagingSenderId: '132809015904',
    projectId: 'digital-garden-de4ed',
    storageBucket: 'digital-garden-de4ed.appspot.com',
    iosBundleId: 'nickthecan.com.digitalGarden.RunnerTests',
  );
}
